blank_issues_enabled: false
contact_links:
  - name: Support Server
    url: https://discord.gg/EsNDvBaHVU
    about: If you need help regarding Aliucord or plugins that are not mine, please join the support server.