name: Feature Request
description: Request a feature for one of my plugins. To request new plugins, please go to Aliucord/plugin-requests.
labels: [enhancement]
body:
  - type: input
    id: discord
    attributes:
      label: Discord Account
      description: Leave your discord account for follow-up if neccesary. Not required
      placeholder: deeznuts#0000
    validations:
      required: false
  - type: input
    id: applicable-plugin
    attributes:
      label: What plugin does this apply to?
      description: What plugin of mine are you requesting a feature for?
      placeholder: AutoShowSpoilers
    validations:
      required: true
  - type: textarea
    id: feature-basic-description
    attributes:
      label: What feature would you like to see?
      description: Also, you'd like to, give us a bit more information on what you'd like this feature to do and/or how you want it to work.
      placeholder: I think ... would be a cool feature to add. This would be awesome, thanks!
    validations:
      required: true